# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-08 17:36
from __future__ import unicode_literals

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lat', models.FloatField(max_length=255)),
                ('lng', models.FloatField(max_length=255)),
                ('original', models.ImageField(max_length=1000, upload_to='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('thumbnail', models.ImageField(max_length=1000, upload_to='')),
            ],
        ),
    ]
