# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 22:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='lng',
            new_name='long',
        ),
    ]
