# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-27 22:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_auto_20161027_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='image',
            new_name='original',
        ),
    ]
